spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seminar?serverTimezone=UTC
    username: root
    password: seminar
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
      
auth.jwt:
  issuer: root
  jwtSecret: SEMINAR_SECRET_KEY
  jwtExpiration: 300000
  # TODO 누락된 정보를 추가해 주세요.